package life.showlin.community.mycommunity.mapper;

import java.util.List;
import life.showlin.community.mycommunity.model.Tuser;
import life.showlin.community.mycommunity.model.TuserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    long countByExample(TuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    int deleteByExample(TuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    int insert(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    int insertSelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    List<Tuser> selectByExampleWithRowbounds(TuserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    List<Tuser> selectByExample(TuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    Tuser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") Tuser record, @Param("example") TuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    int updateByExample(@Param("record") Tuser record, @Param("example") TuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    int updateByPrimaryKeySelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    int updateByPrimaryKey(Tuser record);
}