package life.showlin.community.mycommunity.model;

public class Tuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.id
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.account_id
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.avatar_url
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.name
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.token
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.gmt_create
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.gmt_modified
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.id
     *
     * @return the value of tuser.id
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.id
     *
     * @param id the value for tuser.id
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.account_id
     *
     * @return the value of tuser.account_id
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.account_id
     *
     * @param accountId the value for tuser.account_id
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.avatar_url
     *
     * @return the value of tuser.avatar_url
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.avatar_url
     *
     * @param avatarUrl the value for tuser.avatar_url
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.name
     *
     * @return the value of tuser.name
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.name
     *
     * @param name the value for tuser.name
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.token
     *
     * @return the value of tuser.token
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.token
     *
     * @param token the value for tuser.token
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.gmt_create
     *
     * @return the value of tuser.gmt_create
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.gmt_create
     *
     * @param gmtCreate the value for tuser.gmt_create
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.gmt_modified
     *
     * @return the value of tuser.gmt_modified
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.gmt_modified
     *
     * @param gmtModified the value for tuser.gmt_modified
     *
     * @mbg.generated Wed Feb 05 00:48:12 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}